data:
  image: busybox
  volumes:
    - /mnt/sda1/shared/data:/data
    - /mnt/sda1/shared/mysql:/var/lib/mysql
    - /mnt/sda1/shared/postgres:/var/lib/postgresql
    - /mnt/sda1/shared/elasticsearch:/usr/share/elasticsearch/data
  command: /bin/echo

mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
  # /var/lib/mysql
  volumes_from:
    - data
  ports:
    - "3306:3306"

postgres:
  image: postgres
  # /var/lib/postgresql/data
  volumes_from:
    - data
  ports:
      - "5432:5432"

mongo:
  image: mongo
  # /data/db
  volumes_from:
    - data
  ports:
    - "27017:27017"

elasticsearch:
  image: elasticsearch
  # /usr/share/elasticsearch/data
  volumes_from:
    - data
  ports:
    - "9200:9200"
    - "9300:9300"

redis:
  image: redis
  # /data
  volumes_from:
    - data
  ports:
    - "6379:6379"

fluentd:
  image: fluent/fluentd
  ports:
    - "24224:24224"
