mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
  # /var/lib/mysql
  volumes:
    - ~/data/mysql:/var/lib/mysql
  ports:
    - "3306:3306"

postgres:
  image: postgres
  # /var/lib/postgresql/data
  volumes:
    - ~/data/postgres:/var/lib/postgresql/data
  ports:
      - "5432:5432"

mongo:
  image: mongo
  # /data/db
  volumes:
    - ~/data/mongodb:/data/db
  ports:
    - "27017:27017"

elasticsearch:
  image: elasticsearch
  # /usr/share/elasticsearch/data
  volumes:
    - ~/data/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"

redis:
  image: redis
  # /data
  volumes:
    - ~/data/redis:/data
  ports:
    - "6379:6379"

fluentd:
  image: fluent/fluentd
  ports:
    - "24224:24224"
